# To convert any tabular file to json - copied from csv-to-json.py

In [ ]:
import csv, sys
import json
import utils as utils
from collections import OrderedDict
import argparse

def csv_file_to_json(inFileName, outFileName):
    # jsonpickle.set_encoder_options("simplejson", sort_keys=True, indent = 4)
    jsonData = []
    row_no = 0

    with open(inFileName, 'rb') as f:
        reader = csv.reader(f, delimiter=',')
        try:
            for currRow in reader:
                if utils.is_blank_array(currRow):
                    continue;
                if (row_no == 0):
                    header = currRow
                    # print header
                else:
                    # print currRow
                    jsonData.append(dict(zip(header, currRow)))
                row_no += 1

        except csv.Error as e:
            sys.exit('file %s, line %d: %s' % (inFileName, reader.line_num, e))

    with open(outFileName, 'w') as outfile:
        json.dump(jsonData, outfile)
    # print json.dumps(jsonData)

# To just play with data in csv file

In [15]:
import csv, sys

inFileName = "../data/nikkei-tickers.csv"
row_no = 0

with open(inFileName, 'rb') as f:
    reader = csv.reader(f, delimiter=',')
    for currRow in reader:
        try:
            float(currRow[0][0:4])
            print("{},{}".format(currRow[0][4:], currRow[0][0:4]))
        except:
            pass

KYOWA HAKKO KIRIN CO.,4151
TAKEDA PHARMACEUTICAL CO.,4502
ASTELLAS PHARMA INC.,4503
SUMITOMO DAINIPPON PHARMA CO.,4506
SHIONOGI & CO.,4507
CHUGAI PHARMACEUTICAL CO.,4519
EISAI CO.,4523
DAIICHI SANKYO CO.,4568
OTSUKA HOLDINGS CO.,4578
NISSHINBO HOLDINGS INC.,3105
MINEBEA MITSUMI INC.,6479
HITACHI,6501
MITSUBISHI ELECTRIC CORP.,6503
FUJI ELECTRIC CO.,6504
YASKAWA ELECTRIC CORP.,6506
MEIDENSHA CORP.,6508
GS YUASA CORP.,6674
NEC CORP.,6701
FUJITSU LTD.,6702
OKI ELECTRIC IND. CO.,6703
SEIKO EPSON CORP.,6724
PANASONIC CORP.,6752
SONY CORP.,6758
TDK CORP.,6762
ALPS ELECTRIC CO.,6770
PIONEER CORP.,6773
YOKOGAWA ELECTRIC CORP.,6841
ADVANTEST CORP.,6857
DENSO CORP.,6902
CASIO COMPUTER CO.,6952
FANUC CORP.,6954
KYOCERA CORP.,6971
TAIYO YUDEN CO.,6976
SCREEN HOLDINGS CO.,7735
CANON INC.,7751
RICOH CO.,7752
TOKYO ELECTRON LTD.,8035
NISSAN MOTOR CO.,7201
ISUZU MOTORS LTD.,7202
TOYOTA MOTOR CORP.,7203
HINO MOTORS,7205
MITSUBISHI MOTORS CORP.,7211
MAZDA MOTOR CORP.,7261
HONDA MOTOR CO.,7267
SUZUKI MOTOR CORP.,7269
SUBARU CORP.,7270
YAMAHA MOTOR CO.,7272
TERUMO CORP.,4543
KONICA MINOLTA,4902
NIKON CORP.,7731
OLYMPUS CORP.,7733
CITIZEN WATCH CO.,7762
SKY PERFECT JSAT HOLDINGS INC.,9412
NIPPON TELEGRAPH & TELEPHONE CORP.,9432
KDDI CORP.,9433
NTT DOCOMO,9437
NTT DATA CORP.,9613
SOFTBANK GROUP CORP.,9984
CONCORDIA FINANCIAL GROUP,7186
SHINSEI BANK,8303
AOZORA BANK,8304
MITSUBISHI UFJ FINANCIAL GROUP,8306
RESONA HOLDINGS,8308
SUMITOMO MITSUI TRUST HOLDINGS,8309
SUMITOMO MITSUI FINANCIAL GROUP,8316
THE CHIBA BANK,8331
FUKUOKA FINANCIAL GROUP,8354
THE SHIZUOKA BANK,8355
MIZUHO FINANCIAL GROUP,8411
CREDIT SAISON CO.,8253
DAIWA SECURITIES GROUP INC.,8601
NOMURA HOLDINGS,8604
MATSUI SECURITIES CO.,8628
SOMPO HOLDINGS,8630
MS&AD INSURANCE GROUP HOLDINGS,8725
SONY FINANCIAL HOLDINGS INC.,8729
DAI-ICHI LIFE HOLDINGS,8750
TOKIO MARINE HOLDINGS,8766
T&D HOLDINGS,8795
NIPPON SUISAN KAISHA,1332
MARUHA NICHIRO CORP.,1333
NISSHIN SEIFUN GROUP INC.,2002
MEIJI HOLDINGS CO.,2269
NH FOODS LTD.,2282
SAPPORO HOLDINGS LTD.,2501
ASAHI GROUP HOLDINGS,2502
KIRIN HOLDINGS CO.,2503
TAKARA HOLDINGS INC.,2531
KIKKOMAN CORP.,2801
AJINOMOTO CO.,2802
NICHIREI CORP.,2871
JAPAN TOBACCO INC.,2914
J.FRONT RETAILING CO.,3086
ISETAN MITSUKOSHI HOLDINGS LTD.,3099
SEVEN & I HOLDINGS CO.,3382
FAMILYMART UNY HOLDINGS CO.,8028
TAKASHIMAYA CO.,8233
MARUI GROUP CO.,8252
AEON CO.,8267
FAST RETAILING CO.,9983
DENA CO.,2432
DENTSU INC.,4324
YAHOO JAPAN CORP.,4689
TREND MICRO INC.,4704
RAKUTEN,4755
TOHO CO.,9602
TOKYO DOME CORP.,9681
SECOM CO.,9735
KONAMI HOLDINGS CORP.,9766
INPEX CORP.,1605
TOYOBO CO.,3101
UNITIKA,3103
TEIJIN LTD.,3401
TORAY INDUSTRIES,3402
OJI HOLDINGS CORP.,3861
NIPPON PAPER INDUSTRIES CO.,3863
HOKUETSU KISHU PAPER CO.,3865
KURARAY CO.,3405
ASAHI KASEI CORP.,3407
SHOWA DENKO K.K.,4004
SUMITOMO CHEMICAL CO.,4005
NISSAN CHEMICAL IND.,4021
TOSOH CORP.,4042
TOKUYAMA CORP.,4043
DENKA CO.,4061
SHIN-ETSU CHEMICAL CO.,4063
MITSUI CHEMICALS,4183
MITSUBISHI CHEMICAL HOLDINGS CORP.,4188
UBE INDUSTRIES,4208
NIPPON KAYAKU CO.,4272
KAO CORP.,4452
FUJIFILM HOLDINGS CORP.,4901
SHISEIDO CO.,4911
NITTO DENKO CORP.,6988
SHOWA SHELL SEKIYU K.K.,5002
JXTG HOLDINGS,5020
THE YOKOHAMA RUBBER CO.,5101
BRIDGESTONE CORP.,5108
ASAHI GLASS CO.,5201
NIPPON SHEET GLASS CO.,5202
NIPPON ELECTRIC GLASS CO.,5214
SUMITOMO OSAKA CEMENT CO.,5232
TAIHEIYO CEMENT CORP.,5233
TOKAI CARBON CO.,5301
TOTO LTD.,5332
NGK INSULATORS,5333
NIPPON STEEL & SUMITOMO METAL CORP.,5401
KOBE STEEL,5406
JFE HOLDINGS,5411
NISSHIN STEEL CO.,5413
PACIFIC METALS CO.,5541
SUMCO CORP.,3436
NIPPON LIGHT METAL HOLDINGS CO.,5703
MITSUI MINING & SMELTING CO.,5706
TOHO ZINC CO.,5707
MITSUBISHI MATERIALS CORP.,5711
SUMITOMO METAL MINING CO.,5713
DOWA HOLDINGS CO.,5714
FURUKAWA CO.,5715
FURUKAWA ELECTRIC CO.,5801
SUMITOMO ELECTRIC IND.,5802
FUJIKURA LTD.,5803
TOYO SEIKAN GROUP HOLDINGS,5901
SOJITZ CORP.,2768
ITOCHU CORP.,8001
MARUBENI CORP.,8002
TOYOTA TSUSHO CORP.,8015
MITSUI & CO.,8031
SUMITOMO CORP.,8053
MITSUBISHI CORP.,8058
COMSYS HOLDINGS CORP.,1721
TAISEI CORP.,1801
OBAYASHI CORP.,1802
SHIMIZU CORP.,1803
HASEKO CORP.,1808
KAJIMA CORP.,1812
DAIWA HOUSE IND. CO.,1925
SEKISUI HOUSE,1928
JGC CORP.,1963
THE JAPAN STEEL WORKS,5631
OKUMA CORP.,6103
AMADA HOLDINGS CO.,6113
KOMATSU LTD.,6301
SUMITOMO HEAVY IND.,6302
HITACHI CONST. MACH. CO.,6305
KUBOTA CORP.,6326
EBARA CORP.,6361
CHIYODA CORP.,6366
DAIKIN INDUSTRIES,6367
NSK LTD.,6471
NTN CORP.,6472
JTEKT CORP.,6473
HITACHI ZOSEN CORP.,7004
MITSUBISHI HEAVY IND.,7011
IHI CORP.,7013
MITSUI ENG. & SHIPBUILD. CO.,7003
KAWASAKI HEAVY IND.,7012
TAKEDA PHARMACEUTICAL CO.,4502
ASTELLAS PHARMA INC.,4503
SUMITOMO DAINIPPON PHARMA CO.,4506
SHIONOGI & CO.,4507
CHUGAI PHARMACEUTICAL CO.,4519
EISAI CO.,4523
DAIICHI SANKYO CO.,4568
OTSUKA HOLDINGS CO.,4578
NISSHINBO HOLDINGS INC.,3105
MINEBEA MITSUMI INC.,6479
HITACHI,6501
MITSUBISHI ELECTRIC CORP.,6503
FUJI ELECTRIC CO.,6504
YASKAWA ELECTRIC CORP.,6506
MEIDENSHA CORP.,6508
GS YUASA CORP.,6674
NEC CORP.,6701
FUJITSU LTD.,6702
OKI ELECTRIC IND. CO.,6703
SEIKO EPSON CORP.,6724
PANASONIC CORP.,6752
SONY CORP.,6758
TDK CORP.,6762
ALPS ELECTRIC CO.,6770
PIONEER CORP.,6773
YOKOGAWA ELECTRIC CORP.,6841
ADVANTEST CORP.,6857
DENSO CORP.,6902
CASIO COMPUTER CO.,6952
FANUC CORP.,6954
KYOCERA CORP.,6971
TAIYO YUDEN CO.,6976
SCREEN HOLDINGS CO.,7735
CANON INC.,7751
RICOH CO.,7752
TOKYO ELECTRON LTD.,8035
NISSAN MOTOR CO.,7201
ISUZU MOTORS LTD.,7202
TOYOTA MOTOR CORP.,7203
HINO MOTORS,7205
MITSUBISHI MOTORS CORP.,7211
MAZDA MOTOR CORP.,7261
HONDA MOTOR CO.,7267
SUZUKI MOTOR CORP.,7269
SUBARU CORP.,7270
YAMAHA MOTOR CO.,7272
TERUMO CORP.,4543
KONICA MINOLTA,4902
NIKON CORP.,7731
OLYMPUS CORP.,7733
CITIZEN WATCH CO.,7762
SKY PERFECT JSAT HOLDINGS INC.,9412
NIPPON TELEGRAPH & TELEPHONE CORP.,9432
KDDI CORP.,9433
NTT DOCOMO,9437
NTT DATA CORP.,9613
SOFTBANK GROUP CORP.,9984
CONCORDIA FINANCIAL GROUP,7186
SHINSEI BANK,8303
AOZORA BANK,8304
MITSUBISHI UFJ FINANCIAL GROUP,8306
RESONA HOLDINGS,8308
SUMITOMO MITSUI TRUST HOLDINGS,8309
SUMITOMO MITSUI FINANCIAL GROUP,8316
THE CHIBA BANK,8331
FUKUOKA FINANCIAL GROUP,8354
THE SHIZUOKA BANK,8355
MIZUHO FINANCIAL GROUP,8411
CREDIT SAISON CO.,8253
DAIWA SECURITIES GROUP INC.,8601
NOMURA HOLDINGS,8604
MATSUI SECURITIES CO.,8628
SOMPO HOLDINGS,8630
MS&AD INSURANCE GROUP HOLDINGS,8725
SONY FINANCIAL HOLDINGS INC.,8729
DAI-ICHI LIFE HOLDINGS,8750
TOKIO MARINE HOLDINGS,8766
T&D HOLDINGS,8795
NIPPON SUISAN KAISHA,1332
MARUHA NICHIRO CORP.,1333
NISSHIN SEIFUN GROUP INC.,2002
MEIJI HOLDINGS CO.,2269
NH FOODS LTD.,2282
SAPPORO HOLDINGS LTD.,2501
ASAHI GROUP HOLDINGS,2502
KIRIN HOLDINGS CO.,2503
TAKARA HOLDINGS INC.,2531
KIKKOMAN CORP.,2801
AJINOMOTO CO.,2802
NICHIREI CORP.,2871
JAPAN TOBACCO INC.,2914
J.FRONT RETAILING CO.,3086
ISETAN MITSUKOSHI HOLDINGS LTD.,3099
SEVEN & I HOLDINGS CO.,3382
FAMILYMART UNY HOLDINGS CO.,8028
TAKASHIMAYA CO.,8233
MARUI GROUP CO.,8252
AEON CO.,8267
FAST RETAILING CO.,9983
DENA CO.,2432
DENTSU INC.,4324
YAHOO JAPAN CORP.,4689
TREND MICRO INC.,4704
RAKUTEN,4755
TOHO CO.,9602
TOKYO DOME CORP.,9681
SECOM CO.,9735
KONAMI HOLDINGS CORP.,9766
INPEX CORP.,1605
TOYOBO CO.,3101
UNITIKA,3103
TEIJIN LTD.,3401
TORAY INDUSTRIES,3402
OJI HOLDINGS CORP.,3861
NIPPON PAPER INDUSTRIES CO.,3863
HOKUETSU KISHU PAPER CO.,3865
KURARAY CO.,3405
ASAHI KASEI CORP.,3407
SHOWA DENKO K.K.,4004
SUMITOMO CHEMICAL CO.,4005
NISSAN CHEMICAL IND.,4021
TOSOH CORP.,4042
TOKUYAMA CORP.,4043
DENKA CO.,4061
SHIN-ETSU CHEMICAL CO.,4063
MITSUI CHEMICALS,4183
MITSUBISHI CHEMICAL HOLDINGS CORP.,4188
UBE INDUSTRIES,4208
NIPPON KAYAKU CO.,4272
KAO CORP.,4452
FUJIFILM HOLDINGS CORP.,4901
SHISEIDO CO.,4911
NITTO DENKO CORP.,6988
SHOWA SHELL SEKIYU K.K.,5002
JXTG HOLDINGS,5020
THE YOKOHAMA RUBBER CO.,5101
BRIDGESTONE CORP.,5108
ASAHI GLASS CO.,5201
NIPPON SHEET GLASS CO.,5202
NIPPON ELECTRIC GLASS CO.,5214
SUMITOMO OSAKA CEMENT CO.,5232
TAIHEIYO CEMENT CORP.,5233
TOKAI CARBON CO.,5301
TOTO LTD.,5332
NGK INSULATORS,5333
NIPPON STEEL & SUMITOMO METAL CORP.,5401
KOBE STEEL,5406
JFE HOLDINGS,5411
NISSHIN STEEL CO.,5413
PACIFIC METALS CO.,5541
SUMCO CORP.,3436
NIPPON LIGHT METAL HOLDINGS CO.,5703
MITSUI MINING & SMELTING CO.,5706
TOHO ZINC CO.,5707
MITSUBISHI MATERIALS CORP.,5711
SUMITOMO METAL MINING CO.,5713
DOWA HOLDINGS CO.,5714
FURUKAWA CO.,5715
FURUKAWA ELECTRIC CO.,5801
SUMITOMO ELECTRIC IND.,5802
FUJIKURA LTD.,5803
TOYO SEIKAN GROUP HOLDINGS,5901
SOJITZ CORP.,2768
ITOCHU CORP.,8001
MARUBENI CORP.,8002
TOYOTA TSUSHO CORP.,8015
MITSUI & CO.,8031
SUMITOMO CORP.,8053
MITSUBISHI CORP.,8058
COMSYS HOLDINGS CORP.,1721
TAISEI CORP.,1801
OBAYASHI CORP.,1802
SHIMIZU CORP.,1803
HASEKO CORP.,1808
KAJIMA CORP.,1812
DAIWA HOUSE IND. CO.,1925
SEKISUI HOUSE,1928
JGC CORP.,1963
THE JAPAN STEEL WORKS,5631
OKUMA CORP.,6103
AMADA HOLDINGS CO.,6113
KOMATSU LTD.,6301
SUMITOMO HEAVY IND.,6302
HITACHI CONST. MACH. CO.,6305
KUBOTA CORP.,6326
EBARA CORP.,6361
CHIYODA CORP.,6366
DAIKIN INDUSTRIES,6367
NSK LTD.,6471
NTN CORP.,6472
JTEKT CORP.,6473
HITACHI ZOSEN CORP.,7004
MITSUBISHI HEAVY IND.,7011
IHI CORP.,7013
MITSUI ENG. & SHIPBUILD. CO.,7003
KAWASAKI HEAVY IND.,7012
TOPPAN PRINTING CO.,7911
DAI NIPPON PRINTING CO.,7912
YAMAHA CORP.,7951
TOKYU FUDOSAN HOLDINGS CORP.,3289
MITSUI FUDOSAN CO.,8801
MITSUBISHI ESTATE CO.,8802
TOKYO TATEMONO CO.,8804
SUMITOMO REALTY & DEVELOPMENT CO.,8830
TOBU RAILWAY CO.,9001
TOKYU CORP.,9005
ODAKYU ELECTRIC RAILWAY CO.,9007
KEIO CORP.,9008
KEISEI ELECTRIC RAILWAY CO.,9009
EAST JAPAN RAILWAY CO.,9020
WEST JAPAN RAILWAY CO.,9021
CENTRAL JAPAN RAILWAY CO.,9022
NIPPON EXPRESS CO.,9062
YAMATO HOLDINGS CO.,9064
NIPPON YUSEN K.K.,9101
MITSUI O.S.K.LINES,9104
KAWASAKI KISEN KAISHA,9107
ANA HOLDINGS INC.,9202
MITSUBISHI LOGISTICS CORP.,9301
TOKYO ELECTRIC POWER COMPANY HOLDINGS,9501
CHUBU ELECTRIC POWER CO.,9502
THE KANSAI ELECTRIC POWER CO.,9503
TOKYO GAS CO.,9531
OSAKA GAS CO.,9532
TOPPAN PRINTING CO.,7911
DAI NIPPON PRINTING CO.,7912
YAMAHA CORP.,7951
TOKYU FUDOSAN HOLDINGS CORP.,3289
MITSUI FUDOSAN CO.,8801
MITSUBISHI ESTATE CO.,8802
TOKYO TATEMONO CO.,8804
SUMITOMO REALTY & DEVELOPMENT CO.,8830
TOBU RAILWAY CO.,9001
TOKYU CORP.,9005
ODAKYU ELECTRIC RAILWAY CO.,9007
KEIO CORP.,9008
KEISEI ELECTRIC RAILWAY CO.,9009
EAST JAPAN RAILWAY CO.,9020
WEST JAPAN RAILWAY CO.,9021
CENTRAL JAPAN RAILWAY CO.,9022
NIPPON EXPRESS CO.,9062
YAMATO HOLDINGS CO.,9064
NIPPON YUSEN K.K.,9101
MITSUI O.S.K.LINES,9104
KAWASAKI KISEN KAISHA,9107
ANA HOLDINGS INC.,9202
MITSUBISHI LOGISTICS CORP.,9301
TOKYO ELECTRIC POWER COMPANY HOLDINGS,9501
CHUBU ELECTRIC POWER CO.,9502
THE KANSAI ELECTRIC POWER CO.,9503
TOKYO GAS CO.,9531
OSAKA GAS CO.,9532

In [1]:
import pandas as pd

inFileName = "../utils/scpyutils/atable.csv"

df = pd.read_csv(inFileName)
df.head()

  header 1 header 2 header 3 header 4
0        1        2        3        4
1      abc      def      efg      ghi
2               NaN               NaN

In [1]:
import pandas as pd

server_data_path = "/home/shirishc/Dropbox/Drop-Personal/Shared-Projects/Noviscient/dev-Noviscient/novi-sol-server-data-retriever/data/"
df = pd.read_csv(server_data_path + "7267_rf_scores.csv", header=None)

In [2]:
rf_scores = df.to_dict(orient="split")
rf_scores["data"]

[['mkt_EMA_120', 0.34700000000000003],
 ['mkt_SMA_120', 0.293],
 ['mkt_SMA_60', 0.282],
 ['mkt_EMA_20', 0.253],
 ['mkt_EMA_10', 0.247],
 ['mkt_DEMA_60', 0.242],
 ['mkt_DEMA_120', 0.235],
 ['mkt_SMA_20', 0.233],
 ['mkt_EMA_60', 0.22],
 ['mkt_SMA_10', 0.213],
 ['mkt_AD', 0.20600000000000002],
 ['mkt_SMA_5', 0.139],
 ['mkt_OBV', 0.11199999999999999],
 ['mkt_ATR_60', 0.109],
 ['mkt_ATR_120', 0.057],
 ['alt_ideavolume', 0.036000000000000004],
 ['mkt_ATR_20', 0.034],
 ['mkt_ATR_10', 0.022000000000000002],
 ['alt_Sentiment Low', 0.017],
 ['mkt_ATR_5', 0.013999999999999999],
 ['alt_Sentiment', 0.004],
 ['mkt_AROONOSC_5', -0.006],
 ['mkt_MACD_10', -0.008],
 ['alt_Sentiment High', -0.012],
 ['mkt_J_5', -0.022000000000000002],
 ['mkt_ADX_5', -0.026000000000000002],
 ['alt_indicator', -0.038],
 ['mkt_J_10', -0.061]]

In [3]:
df

                     0      1
0          mkt_EMA_120  0.347
1          mkt_SMA_120  0.293
2           mkt_SMA_60  0.282
3           mkt_EMA_20  0.253
4           mkt_EMA_10  0.247
5          mkt_DEMA_60  0.242
6         mkt_DEMA_120  0.235
7           mkt_SMA_20  0.233
8           mkt_EMA_60  0.220
9           mkt_SMA_10  0.213
10              mkt_AD  0.206
11           mkt_SMA_5  0.139
12             mkt_OBV  0.112
13          mkt_ATR_60  0.109
14         mkt_ATR_120  0.057
15      alt_ideavolume  0.036
16          mkt_ATR_20  0.034
17          mkt_ATR_10  0.022
18   alt_Sentiment Low  0.017
19           mkt_ATR_5  0.014
20       alt_Sentiment  0.004
21      mkt_AROONOSC_5 -0.006
22         mkt_MACD_10 -0.008
23  alt_Sentiment High -0.012
24             mkt_J_5 -0.022
25           mkt_ADX_5 -0.026
26       alt_indicator -0.038
27            mkt_J_10 -0.061

In [4]:
df[0]

0            mkt_EMA_120
1            mkt_SMA_120
2             mkt_SMA_60
3             mkt_EMA_20
4             mkt_EMA_10
5            mkt_DEMA_60
6           mkt_DEMA_120
7             mkt_SMA_20
8             mkt_EMA_60
9             mkt_SMA_10
10                mkt_AD
11             mkt_SMA_5
12               mkt_OBV
13            mkt_ATR_60
14           mkt_ATR_120
15        alt_ideavolume
16            mkt_ATR_20
17            mkt_ATR_10
18     alt_Sentiment Low
19             mkt_ATR_5
20         alt_Sentiment
21        mkt_AROONOSC_5
22           mkt_MACD_10
23    alt_Sentiment High
24               mkt_J_5
25             mkt_ADX_5
26         alt_indicator
27              mkt_J_10
Name: 0, dtype: object

In [7]:
dict(zip(df[0], df[1]))

{'alt_Sentiment': 0.0040000000000000001,
 'alt_Sentiment High': -0.012,
 'alt_Sentiment Low': 0.017000000000000001,
 'alt_ideavolume': 0.036000000000000004,
 'alt_indicator': -0.037999999999999999,
 'mkt_AD': 0.20600000000000002,
 'mkt_ADX_5': -0.026000000000000002,
 'mkt_AROONOSC_5': -0.0060000000000000001,
 'mkt_ATR_10': 0.022000000000000002,
 'mkt_ATR_120': 0.057000000000000002,
 'mkt_ATR_20': 0.034000000000000002,
 'mkt_ATR_5': 0.013999999999999999,
 'mkt_ATR_60': 0.109,
 'mkt_DEMA_120': 0.23499999999999999,
 'mkt_DEMA_60': 0.24199999999999999,
 'mkt_EMA_10': 0.247,
 'mkt_EMA_120': 0.34700000000000003,
 'mkt_EMA_20': 0.253,
 'mkt_EMA_60': 0.22,
 'mkt_J_10': -0.060999999999999999,
 'mkt_J_5': -0.022000000000000002,
 'mkt_MACD_10': -0.0080000000000000002,
 'mkt_OBV': 0.11199999999999999,
 'mkt_SMA_10': 0.21299999999999999,
 'mkt_SMA_120': 0.29299999999999998,
 'mkt_SMA_20': 0.23300000000000001,
 'mkt_SMA_5': 0.13900000000000001,
 'mkt_SMA_60': 0.28199999999999997}